#
# embedXcode
# ----------------------------------
# Embedded Computing on Xcode
#
# Copyright © Rei VILO, 2010-2015
# http://embedxcode.weebly.com
# All rights reserved
#
# Last update: Dec 15, 2015 release 4.1.1
#

# ----------------------------------
# DO NOT EDIT THIS FILE.
# ----------------------------------

EMBEDXCODE_RELEASE      = 4.1.1
EMBEDXCODE_DATE         = Dec 15, 2015
EMBEDXCODE_MESSAGE      = Stability improvement for ESP8266 2.0.0

# ~
EMBEDXCODE_EDITION      = embedXcode for Wiring / Arduino
EMBEDXCODE_REFERENCE    = embedXcode
EMBEDXCODE_TEMPLATE     = ePsiEJEtRXnDNaFGpywBX9vzeNQP4vUb
# ~~


# Arduino.ORG
# ----------------------------------
#
ARDUINO_ORG_RELEASE     = 1.7.8


# Arduino.CC or Genuino with Boards Manager
# ----------------------------------
#
ARDUINO_CC_RELEASE      = 1.6.6

ARDUINO_AVR_RELEASE     = 1.6.9
AVR_GCC_RELEASE         = 4.8.1-arduino5
AVRDUDE_RELEASE         = 6.0.1-arduino5

ARDUINO_SAM_RELEASE     = 1.6.6
ARDUINO_SAMD_RELEASE    = 1.6.2
ARM_GCC_RELEASE         = 4.8.3-2014q1
BOSSAC_RELEASE          = 1.6.1-arduino
CMSIS_RELEASE           = 4.0.0-atmel
OPENOCD_RELEASE         = 0.9.0-arduino

# Boards for Arduino.CC 1.6.5 or Genuino
#
ADAFRUIT_AVR_RELEASE    = 1.4.0

COSA_AVR_RELEASE        = 1.1.1

DIGISPARK_AVR_RELEASE   = 1.6.5
DIGISPARK_SAM_RELEASE   = 1.6.5

ESP8266_RELEASE         = 2.0.0
ESPTOOLS_RELEASE        = 0.4.6
EXTENSA_RELEASE         = 1.20.0-26-gb404fb9-2

INTEL_EDISON_RELEASE    = 1.6.2+1.0
INTEL_GALILEO_RELEASE   = 1.6.2+1.0

LINKIT_ONE_RELEASE      = 1.1.17

LITTLEROBOTFRIENDS_AVR_RELEASE = 1.6.0

PANSTAMP_AVR_RELEASE    = 1.5.3
PANSTAMP_MSP_RELEASE    = 1.0.6

REDBEARLAB_AVR_RELEASE  = 1.0.0
REDBEARLAB_NRF_RELEASE  = 1.0.0

RFDUINO_RELEASE         = 2.3.1

